# Generated by Django 4.1.5 on 2023-01-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
