# Generated by Django 4.1.5 on 2023-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='food_type',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='menu',
            name='details',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
